# Generated by Django 4.1.13 on 2024-07-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_user_ctr', '0002_hostelapp_ac_year_hostelapp_address_hostelapp_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('register_number', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=50)),
                ('complaint', models.TextField()),
            ],
        ),
    ]
