# Generated by Django 4.1.13 on 2024-07-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_user_ctr', '0003_complaintbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAllot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(max_length=10)),
                ('room_number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('usn', models.CharField(max_length=20)),
            ],
        ),
    ]
