# Generated by Django 4.1.13 on 2024-07-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_user_ctr', '0005_roomallot_number_of_entries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomallot',
            name='number_of_entries',
            field=models.IntegerField(default=1),
        ),
    ]
