# Generated by Django 4.1.13 on 2024-07-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_user_ctr', '0007_adminlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelapp',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
